module.exports={
	entry:"./main.js",
	output:{
		path:__dirname,
		filename:"build.js"
	},
	module:{
		loads:{
			{test:/\.vue$/,loader:'vue'},
			{test:/\.js$/,loader:"babel",exclude:/node_module/}
		},
		babel:{
			presets:['es2015'],
			plugins:
		}
	}
}